apiVersion: v1
kind: Service
metadata:
  name: sre-app-service
  namespace: monitoring
  labels:
    app: sre-app
spec:
  selector:
    app: sre-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
